openapi: 3.0.1
info:
  title: CogentProc API
  version: 0.1.1
  description: CogentProc Backend User API Documentation
servers:
  - url: 'http://18.219.24.71/v1/'
    variables: {}
paths:
  /networks/{network_name}:
    description: 'Network Fetch By Network Name'
    get:
      parameters:
        - in: path
          name: network_name
          required: true
          schema:
            type: string
          example: 'cogentprocdemo'
      responses:
        '200':
          description: A Network object.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Network'   
  /login-user:
    description: 'User Login'
    post:
      requestBody:
        description: User email and password
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: 'cogentproc+user@gmail.com'
                password:
                  type: string
                  example: '123456'
                workflow_id:
                  type: string
                  example: '10'
      responses:
        '200':
          description: Success Login.
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      refresh_token: 
                        type: string
                      token: 
                        type: string
                  result:
                    type: string
                   
  /applications:
    description: 'Create Workflow Instance'
    post:
      requestBody:
        description: Instance title
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: 'test1'
                
      responses:
        '200':
          description: Success Workflow instance created.
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      application_id: 
                        type: string
                      
                  result:
                    type: string
                    
  /active-applications:
    description: "Application List"
    get:
       responses:
        '200':
          description: Success in getting the list of active applications.
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                  result:
                    type: string
      
    
components:
  schemas:
    Network:
      type: object
      properties:
        data:
          type: object
          properties:
            network_id:
              type: integer
            name:
              type: string
            description:
              type: string
            api_key:
              type: string
            image:
              type: string
            bg_image:
              type: string
            frontent_url:
              type: string
            theme:
              type: string
            title:
              type: string
            icon:
              type: string
        result:
          type: string
  
  securitySchemes:
    apiKey:
      type: apiKey
      in: header
      name: ApiKey
    frontendURL:
      type: apiKey
      in: header
      name: FrontendURL
    token:
      type: apiKey
      in: header
      name: Token
      
security:
- apiKey: []    
- frontendURL: []
- token: []
          
          
          

