openapi: 3.0.1
info:
  title: CogentProc API
  version: 0.0.1
  description: CogentProc Backend User API Documentation
servers:
  - url: 'http://18.219.24.71/v1/'
    
paths:
  /networks/{network_name}:
    description: 'Network Fetch By Network Name'
    get:
      parameters:
        - in: path
          name: network_name
          required: true
          schema:
            type: string
          example: 'cogentprocdemo'
      responses:
        '200':
          description: A Network object.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Network'   
                
  /networks/apikey/{api_key}:
    description: 'Network Fetch By Network API Key'
    get:
      parameters:
        - in: path
          name: api_key
          required: true
          schema:
            type: string
          example: '5098A4D563DC72B376044AE92B92C0CCB73B09572E3502332CC0CA3D9EC10225'
      responses:
        '200':
          description: A Network object.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Network'
                
  /login-user:
    description: 'User Login'
    post:
      requestBody:
        description: User Login with email and password and optional workflow_id
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
              
      responses:
        '200':
          description: Success Login.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'

 
  /applications:
    description: 'Create Workflow Application'
    post:
      requestBody:
        description: Application title
        required: true
        content:
          application/json:
            schema:
             $ref: '#/components/schemas/ApplicationCreateRequest'
                
      responses:
        '200':
          description: Success Workflow instance created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationCreateResponse'
              
                    
  /active-applications:
    description: "Active Application List"
    get:
       responses:
        '200':
          description: Success in getting the list of active applications.
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/ApplicationObject'
                  result:
                    type: string
  
  /archive-applications:
    description: "Archive Application List"
    get:
       responses:
        '200':
          description: Success in getting the list of archive applications.
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/ApplicationObject'
                  result:
                    type: string
  
  /applications/is-allowed:
    description: "Is user allowed to create Application"
    get:
       responses:
        '200':
          description: Is user allowed to create application.
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      is_allowed: 
                        type: boolean
                  result:
                    type: string
                    
  /application-detail-forms/{application_id}/{role_id}:
    description: 'Application Detail for accessible application'
    get:
      parameters:
        - in: path
          name: application_id
          required: true
          schema:
            type: integer
          example: 10
        - in: path
          name: role_id
          required: true
          schema:
            type: integer
          example: 10
      responses:
        '200':
          description: An Application Detail object.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationDetail'
  
components:
  schemas:
    ApplicationDetail:
      type: object
      properties:
        data:
          type: object
          properties:
            id: 
              type: integer
            network_id: 
              type: integer
            workflow_id: 
              type: integer
            phase_id: 
              type: integer
            role_id: 
              type: integer
            escalate_action_id: 
              type: integer
            escalate_action_title: 
              type: string
            escalate_after: 
              type: integer
            remind_after: 
              type: integer
            remind_again_after: 
              type: integer
            action_required: 
              type: boolean
            auto_generate: 
              type: boolean
            phase_title: 
              type: string
            role_title: 
              type: string
            role_alias: 
              type: string
            title: 
              type: string
            alias: 
              type: string
            show_hide_menu: 
              type: string
            forms:
              type: array
              items:
                $ref: '#/components/schemas/FormObject'
            actions:
              type: array
              items:
                $ref: '#/components/schemas/ActionObject'
        result:
          type: string

    FormObject:
      type: object
      properties:
        id:
          type: integer
        network_id:
          type: integer
        workflow_id:
          type: integer
        form_category_id:
          type: integer
        form_category_title: 
          type: string
        title: 
          type: string
        checkable: 
          type: boolean
        completed: 
          type: boolean
        message: 
          type: string
        fields: 
          type: array
          items:
            $ref: '#/components/schemas/FieldObject'

    FieldObject:
      type: object
      properties:
        id:
          type: integer
        network_id:
          type: integer
        workflow_id:
          type: integer
        workflow_name:
          type: string
        form_id:
          type: integer
        form_title:
          type: string
        committee_name_id:
          type: integer
        committee_name_title:
          type: string
        sort_order:
          type: integer
        rows:
          type: integer
        role_id:
          type: integer
        role_title:
          type: string
        task_id:
          type: integer
        task_title:
          type: string
        department_id:
          type: integer
        department_name:
          type: string
        error_message:
          type: string
        field_error_message:
          type: string
        help_text:
          type: string
        type:
          type: string
        name:
          type: string
        intg_field_id:
          type: integer
        intg_field_name:
          type: string
        option_intg_field_id:
          type: integer
        option_intg_field_name:
          type: string
        value:
          type: string
        completed:
          type: boolean
        label:
          type: string
        default_value:
          type: string
        options:
          type: string
        colspan:
          type: string
        aggregate_rule:
          type: string
        validation_rule:
          type: string
        field_data_type:
          type: string
        required:
          type: boolean
        is_read_only:
          type: boolean
        tooltip:
          type: string
        status:
          type: boolean

    ActionObject:
      type: object
      properties:
        id:
          type: integer
        network_id: 
          type: integer
        workflow_id: 
          type: integer
        task_id: 
          type: integer
        next_phase_id: 
          type: integer
        next_task_id: 
          type: integer
        att_action_id: 
          type: integer
        type: 
          type: string
        type_desc:
          type: string
        title:
          type: string
        require_complete_task:
          type: boolean
        rule:
          type: string
        status:
          type: boolean
        autogenerate:
          type: boolean
        action_message:
          type: array
          items:
           $ref: '#/components/schemas/ActionMessageObject'

    ActionMessageObject:
      type: object
      properties:
        id:
          type: integer
        network_id:
          type: integer
        workflow_id:
          type: integer
        action_id:
          type: integer
        action_title:
          type: string
        phase_id:
          type: integer
        phase_title:
          type: string
        next_task_id:
          type: integer
        next_task_title:
          type: string
        next_task_title_alias:
          type: string
        next_task_email:
          type: string
        next_task_user_id:
          type: integer
        next_task_sms:
          type: string
        next_task_whats_app:
          type: string
        next_task_name:
          type: string
        intg_ext_api_id:
          type: integer
        message:
          type: string
        sms_message:
          type: string
        json_message:
          type: string
        cc_email:
          type: string
        has_committee_info:
          type: boolean
        autogenerate:
          type: boolean
        update_date:
          type: string
        insert_date:
          type: string

    ApplicationObject:
      type: object
      properties:
        application_id:
          type: integer
        role_id: 
          type: integer
        user_id: 
          type: integer
        is_acting: 
          type: string
        title:
          type: string
        start_date:
          type: string
        status:
          type: string
        name_string:
          type: string
        rank:
          type: string
          
    ApplicationCreateResponse:  
      type: object
      properties:
        data:
          type: object
          properties:
            application_id: 
              type: string
        result:
          type: string
          
    ApplicationCreateRequest:
      type: object
      properties:
        title:
         type: string
         example: 'test1'
        
    LoginRequest:
      type: object
      properties:
        email:
          type: string
          example: 'cogentproc+user@gmail.com'
        password:
          type: string
          example: '123456'
        workflow_id:
          type: string
          example: '10'
          
    LoginResponse:
      type: object
      properties:
        data:
          type: object
          properties:
            refresh_token: 
              type: string
            token: 
              type: string
        result:
          type: string
                    
    Network:
      type: object
      properties:
        data:
          type: object
          properties:
            network_id:
              type: integer
            name:
              type: string
            description:
              type: string
            api_key:
              type: string
            image:
              type: string
            bg_image:
              type: string
            frontent_url:
              type: string
            theme:
              type: string
            title:
              type: string
            icon:
              type: string
        result:
          type: string
  
  securitySchemes:
    apiKey:
      type: apiKey
      in: header
      name: ApiKey
    frontendURL:
      type: apiKey
      in: header
      name: FrontendURL
    token:
      type: apiKey
      in: header
      name: Token
      
security:
- apiKey: []    
- frontendURL: []
- token: []
          
          
          

